#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
#                  Main Config                  #
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

Database:
  Mongo:
    URI: ""
  Redis:
    Host: ""
    Port: 1234
    Authentication:
      Enabled: true
      Password: ""